name: Push on main branch

on:
  push:
    branches: 
      -main

jobs:
  Build:
    timeout-minutes: 40
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      - name: generate types
        run: npm run prisma:generate
      - name: Build project
        run: npm run build
